// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SXXFDoYzFbmEA-FwXyeGVY8UnjczsCU',
    appId: '1:14435543950:web:bb9259b18400c5e4d1d2df',
    messagingSenderId: '14435543950',
    projectId: 'timestory-db69c',
    authDomain: 'timestory-db69c.firebaseapp.com',
    storageBucket: 'timestory-db69c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAzMhxY-5IOIRj2F3SiLAlnVeRV8qfeU',
    appId: '1:14435543950:android:91b091a11d83d800d1d2df',
    messagingSenderId: '14435543950',
    projectId: 'timestory-db69c',
    storageBucket: 'timestory-db69c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGOb3IQIui1pCcqHgMAxuJ_4RWvBVS9U',
    appId: '1:14435543950:ios:c4d9a0dda4ad15efd1d2df',
    messagingSenderId: '14435543950',
    projectId: 'timestory-db69c',
    storageBucket: 'timestory-db69c.appspot.com',
    iosBundleId: 'com.example.timestory',
  );
}
